version: "3"

services:
    mysql:
        image: mysql:5.7
        restart: always
        container_name: mysql-symfony-jwt-dev
        networks:
            - default
        environment:
            MYSQL_DATABASE: symfony
            MYSQL_USER: root
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
            - "3306:3306"

    nginx:
        image: nginx:alpine
        container_name: nginx-symfony-jwt-dev
        working_dir: /app
        depends_on:
            - php-fpm
        networks:
            - default
        volumes:
            - .:/app
            - ./docker/dev/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./docker/dev/logs/nginx/:/var/log/nginx/
        ports:
            - "80:80"

    php-fpm:
        image: webdevops/php-dev:7.4
        container_name: php-fpm-symfony-jwt-dev
        working_dir: /app
        networks:
            - default
        depends_on:
            - mysql
        volumes:
            - .:/app
            - ./docker/dev/php/php.ini:/opt/docker/etc/php/dev/php.ini
